{
 "title": "Crypto Sentiment Analysis Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Analyzed Texts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS total_texts\r\nFROM sentiment_results;\r\n"
    }
   ]
  },
  {
   "title": "Sentiment Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sentiment,\r\n  COUNT(*) AS total\r\nFROM sentiment_results\r\nGROUP BY sentiment\r\nORDER BY sentiment;"
    }
   ]
  },
  {
   "title": "Average Sentiment Polarity Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('minute', created_at) AS \"time\",\r\n  AVG(polarity) AS avg_polarity\r\nFROM sentiment_results\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Sentiment Polarity Distribution Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  created_at AS \"time\",\r\n  polarity,\r\n  sentiment\r\nFROM sentiment_results\r\nORDER BY created_at;"
    }
   ]
  }
 ]
}